"""
Proactive Action Graph.

Flow:
  suggest → [user consents?]
    ├── NO  → done (outcome=declined)
    └── YES → plan → tool_select → execute → plan (loop)
                                            → respond → done

The suggest node speaks the consent_prompt from AmbientAnalysis.
No LLM call at suggest — the text is pre-generated by the ambient processor.

Consent detection (simple keyword matching):
  YES: "yes", "sure", "go ahead", "ok", "do it", "please", "yep", "yeah"
  NO:  "no", "not now", "cancel", "stop", "don't", "nope", "nevermind"
  Unrecognised → treated as NO (conservative default)
"""
import json
import logging
from typing import Any

from langgraph.graph import StateGraph, END

from server.action.shared_nodes import (
    plan_node, plan_router, tool_select_node, execute_node, respond_node,
)
from server.action.state import ActionSessionState
from server.llm.client import LLMClient
from server.prompts.action import SUGGEST_FALLBACK

logger = logging.getLogger(__name__)

YES_WORDS = {"yes", "sure", "go ahead", "ok", "do it", "please", "yep", "yeah",
             "alright", "sounds good", "let's do it", "go for it"}
NO_WORDS  = {"no", "not now", "cancel", "stop", "don't", "nope", "nevermind",
             "never mind", "no thanks", "skip", "forget it"}


def detect_consent(reply: str) -> bool | None:
    """
    Returns True (yes), False (no), or None (unclear).
    """
    lower = reply.lower().strip()
    if any(w in lower for w in YES_WORDS):
        return True
    if any(w in lower for w in NO_WORDS):
        return False
    return None


def build_proactive_graph(llm: LLMClient, mcp_base: str = "http://localhost:8888/tools"):
    """
    Build and compile the proactive LangGraph.

    Args:
        llm:      LLMClient for plan/respond nodes
        mcp_base: MCP server base URL (overridden in tests)

    Returns:
        Compiled LangGraph (call .invoke() or .ainvoke())
    """
    builder = StateGraph(ActionSessionState)

    # ── Suggest node ──────────────────────────────────────────────────────────
    def suggest_node(state: ActionSessionState) -> dict:
        """Emit the consent prompt. No LLM call.
        Does NOT reset user_consented — it may already be set if reply is pre-seeded."""
        prompt = state.get("consent_prompt") or SUGGEST_FALLBACK
        logger.info("[SUGGEST] TTS: %r", prompt)
        return {"messages": [{"role": "assistant", "content": prompt}]}

    def suggest_router(state: ActionSessionState) -> str:
        """Route based on whether consent has been given."""
        consented = state.get("user_consented")
        if consented is True:
            return "plan"
        if consented is False:
            return "declined"
        # Still waiting — in a real pipeline this node would pause
        # For graph purposes, treat unclear as declined (conservative)
        return "declined"

    # ── Declined terminal node ────────────────────────────────────────────────
    def declined_node(state: ActionSessionState) -> dict:
        logger.info("[PROACTIVE] user declined — session closed")
        return {"done": True, "outcome": "declined"}

    async def _plan(s):        return await plan_node(s, llm)
    async def _tool_select(s): return await tool_select_node(s)
    async def _execute(s):     return await execute_node(s, mcp_base)
    async def _respond(s):     return await respond_node(s, llm)

    # ── Wire graph ────────────────────────────────────────────────────────────
    builder.add_node("suggest",     suggest_node)
    builder.add_node("plan",        _plan)
    builder.add_node("tool_select", _tool_select)
    builder.add_node("execute",     _execute)
    builder.add_node("respond",     _respond)
    builder.add_node("declined",    declined_node)

    builder.set_entry_point("suggest")

    builder.add_conditional_edges("suggest", suggest_router, {
        "plan":     "plan",
        "declined": "declined",
    })

    builder.add_conditional_edges("plan", plan_router, {
        "tool_select":   "tool_select",
        "respond":       "respond",
        "wait_for_user": END,   # pause for user input (streaming use case)
    })

    builder.add_edge("tool_select", "execute")
    builder.add_edge("execute",     "plan")
    builder.add_edge("respond",     END)
    builder.add_edge("declined",    END)

    return builder.compile()


# ── Async runner ─────────────────────────────────────────────────────────────

async def run_proactive_session(
    initial_state: dict[str, Any],
    user_reply:    str,
    llm:           LLMClient,
    mcp_base:      str = "http://localhost:8888/tools",
) -> ActionSessionState:
    """
    Run a proactive session end-to-end.

    Args:
        initial_state: Seed state (session_id, consent_prompt, task_description, etc.)
        user_reply:    The user's response to the consent prompt ("yes" / "no")
        llm:           LLMClient
        mcp_base:      MCP server base URL

    Returns:
        Final ActionSessionState
    """
    graph = build_proactive_graph(llm, mcp_base)

    # Inject consent decision into state before running
    consented = detect_consent(user_reply)
    if consented is None:
        logger.info("[PROACTIVE] unclear reply %r → treating as declined", user_reply)
        consented = False

    state = {
        "session_id":        initial_state.get("session_id", "test"),
        "user_id":           initial_state.get("user_id", "test_user"),
        "trigger_source":    "proactive_confidence",
        "task_description":  initial_state.get("task_description", ""),
        "consent_prompt":    initial_state.get("consent_prompt", ""),
        "proposed_action":   initial_state.get("proposed_action", ""),
        "messages":          [],
        "step_count":        0,
        "tool_results":      [],
        "final_response":    "",
        "session_memory_ops": [],
        "user_consented":     consented,
        "done":               False,
        "outcome":            "",
        "_next_step":         "",
        "_selected_tools":    [],
    }

    final = await graph.ainvoke(state)
    return final
